name: oracle_auto_login

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pyotp python-dotenv

    - name: Set up Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y libxi6 libgconf-2-4
        echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

    - name: Install Chrome browser
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get install -f

    - name: Run tests
      env:
        CLOUD_ACCOUNT_NAME: ${{ secrets.CLOUD_ACCOUNT_NAME }}
        ORACLE_CLOUD_LOGIN_URL: ${{ secrets.ORACLE_CLOUD_LOGIN_URL }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        OTP_SECRET_KEY: ${{ secrets.OTP_SECRET_KEY }}
      run: |
        export CHROMEDRIVER_PATH=/usr/bin/chromedriver
        python oracle_auto_login.py
